# Generated by Django 5.2.7 on 2025-10-15 06:18

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Content"),
                ),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("theory", "Theory"),
                            ("practice", "Hands-on Practice"),
                            ("quiz", "Quiz"),
                            ("project", "Project"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "example_code_data",
                    models.TextField(
                        blank=True, help_text="JSON formatted code examples"
                    ),
                ),
                ("video_url", models.URLField(blank=True)),
                ("duration_minutes", models.IntegerField()),
                ("is_free", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vcs", "Version Control"),
                            ("ci_cd", "CI/CD"),
                            ("container", "Containerization"),
                            ("orchestration", "Orchestration"),
                            ("iac", "Infrastructure as Code"),
                            ("monitoring", "Monitoring"),
                            ("security", "Security"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("logo", models.ImageField(blank=True, upload_to="technology_logos/")),
                ("official_docs_url", models.URLField(blank=True)),
                ("phase", models.IntegerField(help_text="Learning phase number")),
                ("order", models.IntegerField(help_text="Order within phase")),
            ],
            options={
                "verbose_name_plural": "Technologies",
                "ordering": ["phase", "order"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(help_text="Duration in hours"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prerequisites",
                    models.ManyToManyField(blank=True, to="courses.course"),
                ),
                (
                    "technology",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.technology",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CodeExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("code", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("bash", "Bash"),
                            ("yaml", "YAML"),
                            ("dockerfile", "Dockerfile"),
                            ("json", "JSON"),
                            ("sql", "SQL"),
                            ("html", "HTML"),
                            ("css", "CSS"),
                            ("javascript", "JavaScript"),
                            ("java", "Java"),
                            ("c", "C"),
                            ("c++", "C++"),
                            ("c#", "C#"),
                            ("ruby", "Ruby"),
                            ("php", "PHP"),
                            ("swift", "Swift"),
                            ("go", "Go"),
                            ("rust", "Rust"),
                            ("typescript", "TypeScript"),
                            ("kotlin", "Kotlin"),
                            ("scala", "Scala"),
                            ("perl", "Perl"),
                            ("elixir", "Elixir"),
                            ("crystal", "Crystal"),
                            ("r", "R"),
                            ("julia", "Julia"),
                            ("haskell", "Haskell"),
                            ("lua", "Lua"),
                            ("dart", "Dart"),
                        ],
                        default="python",
                        max_length=50,
                    ),
                ),
                (
                    "explanation",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Explanation"
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_examples",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("order", models.IntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.module",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowDiagram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "diagram_data",
                    models.TextField(help_text="Mermaid.js or similar diagram data"),
                ),
                ("order", models.IntegerField()),
                (
                    "technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.technology",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
