# Generated by Django 5.2.7 on 2025-10-15 10:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_codeexample_description_discussionforum_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discussionpost",
            options={
                "ordering": ["-is_answer", "created_at"],
                "verbose_name": "Discussion Post",
                "verbose_name_plural": "Discussion Posts",
            },
        ),
        migrations.AlterModelOptions(
            name="discussionthread",
            options={
                "ordering": ["-is_pinned", "-created_at"],
                "verbose_name": "Discussion Thread",
                "verbose_name_plural": "Discussion Threads",
            },
        ),
        migrations.AlterModelOptions(
            name="interactiveexercise",
            options={
                "ordering": ["order"],
                "verbose_name": "Interactive Exercise",
                "verbose_name_plural": "Interactive Exercises",
            },
        ),
        migrations.AlterModelOptions(
            name="userexerciseattempt",
            options={
                "ordering": ["-attempted_at"],
                "verbose_name": "Exercise Attempt",
                "verbose_name_plural": "Exercise Attempts",
            },
        ),
        migrations.AlterModelOptions(
            name="uservote",
            options={"verbose_name": "User Vote", "verbose_name_plural": "User Votes"},
        ),
        migrations.AddField(
            model_name="interactiveexercise",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interactiveexercise",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userexerciseattempt",
            name="answers",
            field=models.JSONField(
                blank=True, help_text="User's answers for quiz exercises", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userexerciseattempt",
            name="code_submission",
            field=models.TextField(
                blank=True, help_text="User's code submission for code exercises"
            ),
        ),
        migrations.AlterField(
            model_name="userexerciseattempt",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="courses.interactiveexercise",
            ),
        ),
        migrations.AlterField(
            model_name="userexerciseattempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
